# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userinterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(327, 412)
        MainWindow.setStyleSheet("background-color: rgb(0, 63, 90);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Gb_TextIdentifier = QtWidgets.QGroupBox(self.centralwidget)
        self.Gb_TextIdentifier.setGeometry(QtCore.QRect(18, 11, 290, 170))
        self.Gb_TextIdentifier.setStyleSheet("color: rgb(235, 217, 200);")
        self.Gb_TextIdentifier.setObjectName("Gb_TextIdentifier")
        self.Btn_Delete = QtWidgets.QPushButton(self.Gb_TextIdentifier)
        self.Btn_Delete.setGeometry(QtCore.QRect(200, 125, 75, 23))
        self.Btn_Delete.setStyleSheet("background-color: rgb(222, 102, 0);\n"
"color: rgb(235, 217, 200);")
        self.Btn_Delete.setObjectName("Btn_Delete")
        self.Btn_Add = QtWidgets.QPushButton(self.Gb_TextIdentifier)
        self.Btn_Add.setGeometry(QtCore.QRect(13, 28, 75, 23))
        self.Btn_Add.setStyleSheet("background-color: rgb(222, 102, 0);\n"
"color: rgb(235, 217, 200);")
        self.Btn_Add.setObjectName("Btn_Add")
        self.Line_Path_2 = QtWidgets.QLineEdit(self.Gb_TextIdentifier)
        self.Line_Path_2.setGeometry(QtCore.QRect(93, 29, 181, 21))
        self.Line_Path_2.setText("")
        self.Line_Path_2.setObjectName("Line_Path_2")
        self.List_Text = QtWidgets.QListWidget(self.Gb_TextIdentifier)
        self.List_Text.setGeometry(QtCore.QRect(13, 60, 261, 55))
        self.List_Text.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.List_Text.setObjectName("List_Text")
        item = QtWidgets.QListWidgetItem()
        self.List_Text.addItem(item)
        self.Gb_FileExtraction = QtWidgets.QGroupBox(self.centralwidget)
        self.Gb_FileExtraction.setGeometry(QtCore.QRect(18, 190, 290, 204))
        self.Gb_FileExtraction.setStyleSheet("color: rgb(235, 217, 200);")
        self.Gb_FileExtraction.setObjectName("Gb_FileExtraction")
        self.Btn_Extract = QtWidgets.QPushButton(self.Gb_FileExtraction)
        self.Btn_Extract.setGeometry(QtCore.QRect(13, 160, 261, 23))
        self.Btn_Extract.setStyleSheet("background-color: rgb(222, 102, 0);\n"
"color: rgb(235, 217, 200);")
        self.Btn_Extract.setObjectName("Btn_Extract")
        self.Btn_Destination = QtWidgets.QPushButton(self.Gb_FileExtraction)
        self.Btn_Destination.setGeometry(QtCore.QRect(13, 62, 75, 23))
        self.Btn_Destination.setStyleSheet("background-color: rgb(222, 102, 0);\n"
"color: rgb(235, 217, 200);")
        self.Btn_Destination.setObjectName("Btn_Destination")
        self.Line_Destination = QtWidgets.QLineEdit(self.Gb_FileExtraction)
        self.Line_Destination.setGeometry(QtCore.QRect(93, 63, 181, 21))
        self.Line_Destination.setObjectName("Line_Destination")
        self.Rb_Remove = QtWidgets.QRadioButton(self.Gb_FileExtraction)
        self.Rb_Remove.setGeometry(QtCore.QRect(75, 129, 82, 17))
        self.Rb_Remove.setObjectName("Rb_Remove")
        self.Rb_Save = QtWidgets.QRadioButton(self.Gb_FileExtraction)
        self.Rb_Save.setGeometry(QtCore.QRect(160, 129, 51, 17))
        self.Rb_Save.setObjectName("Rb_Save")
        self.Btn_Source = QtWidgets.QPushButton(self.Gb_FileExtraction)
        self.Btn_Source.setGeometry(QtCore.QRect(13, 28, 75, 23))
        self.Btn_Source.setStyleSheet("background-color: rgb(222, 102, 0);\n"
"color: rgb(235, 217, 200);")
        self.Btn_Source.setObjectName("Btn_Source")
        self.Line_Source = QtWidgets.QLineEdit(self.Gb_FileExtraction)
        self.Line_Source.setGeometry(QtCore.QRect(93, 29, 181, 21))
        self.Line_Source.setObjectName("Line_Source")
        self.Cb_Connect2Web = QtWidgets.QCheckBox(self.Gb_FileExtraction)
        self.Cb_Connect2Web.setGeometry(QtCore.QRect(100, 100, 111, 17))
        self.Cb_Connect2Web.setObjectName("Cb_Connect2Web")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Prototype"))
        self.Gb_TextIdentifier.setTitle(_translate("MainWindow", "Text Identifier"))
        self.Btn_Delete.setText(_translate("MainWindow", "Delete"))
        self.Btn_Add.setText(_translate("MainWindow", "Add"))
        __sortingEnabled = self.List_Text.isSortingEnabled()
        self.List_Text.setSortingEnabled(False)
        item = self.List_Text.item(0)
        item.setText(_translate("MainWindow", "asdasd"))
        self.List_Text.setSortingEnabled(__sortingEnabled)
        self.Gb_FileExtraction.setTitle(_translate("MainWindow", "File Extraction"))
        self.Btn_Extract.setText(_translate("MainWindow", "Extract"))
        self.Btn_Destination.setText(_translate("MainWindow", "Destination"))
        self.Rb_Remove.setText(_translate("MainWindow", "Remove"))
        self.Rb_Save.setText(_translate("MainWindow", "Save"))
        self.Btn_Source.setText(_translate("MainWindow", "Source"))
        self.Cb_Connect2Web.setText(_translate("MainWindow", "Connect2Web"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
